version: '3'

services:

  web:
    image: 'avkosme/nodejs'
    container_name: web
    hostname: hostname.org
    domainname: hostname.org
    privileged: true
    command: bash -c "npm run start"
    working_dir: /opt/webapp
    environment:
      - NODE_ENV=production
      - MONGODB_URI=MONGODB_URI=mongodb://<mlab_user>:<mlab_password>@<mlab_connection_url>
      - SESSION_SECRET=<Put lots of randomness in these>
    volumes: 
      - ./src:/opt/webapp
    dns:
      - 8.8.8.8
    ports:
      - 80:80
      - 443:443
    networks:
      dev:
        ipv4_address: 10.5.0.2  


networks:
  project:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
